
GET http://localhost:5000/health


###
GET http://localhost:5000/listings

###
POST http://localhost:5000/listings

Content-Type: application/json
{
    "name": "testi",
    "price": "100"
}

###

POST http://localhost:5000/users/login

Content-type: application/json
{
    "email": "lol",
    "password": "lol"
}

###

POST http://localhost:5000/users/signup
Content-Type: application/json

{
  "name": "John Wayneee",
  "email": "john@wayneee.com",
  "password": "john@wayneee"
}